### ISSUE TITLE
Configure Error / CMake Error: Unknown argument --option="path with 'space'"

### ISSUE THREAD

**Issue by saurabhghumnar** [flavorjones/mini_portile#111]
```
[root@b2c3899e3f22 mini_portile2]# bundle exec rake test:unit
ruby -w -W2 -I. -Ilib -e "require 'test/test_cook.rb';require 'test/test_proxy.rb';require 'test/test_download.rb';require 'test/test_cmake.rb';require 'test/test_digest.rb';" --  -v
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:44: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Object#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/dsl.rb:47: warning: Object#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Object#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:272: warning: Object#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/rubygems_ext.rb:51: warning: Object#untaint is deprecated and will be removed in Ruby 3.2.
/home/tester/mini_portile2/lib/mini_portile2/mini_portile.rb:451: warning: assigned but unused variable - progress
/home/tester/mini_portile2/lib/mini_portile2/mini_portile.rb:505: warning: assigned but unused variable - progress
/usr/local/rvm/gems/ruby-2.7.2/gems/bundler-1.17.3/lib/bundler/rubygems_ext.rb:51: warning: Object#untaint is deprecated and will be removed in Ruby 3.2.
Run options: -v --seed 62324

```

# Running:

```

Extracting test-mini-portile-1.0.0.tar.gz into tmp/ppc64le-redhat-linux/ports/test mini portile/1.0.0... OK
Running git apply with /home/tester/mini_portile2/test/assets/patch 1.diff... OK
Running 'configure' for test mini portile 1.0.0... OK
Running 'compile' for test mini portile 1.0.0... OK
Running 'install' for test mini portile 1.0.0... OK
TestCookWithBrokenGitDir#test_patch = 0.01 s = .
[2021-12-20 08:34:24] INFO  WEBrick 1.6.0
[2021-12-20 08:34:24] INFO  ruby 2.7.2 (2020-10-01) [powerpc64le-linux]
[2021-12-20 08:34:24] INFO  WEBrick::HTTPServer#start: pid=210 port=23523
TestDigest#test_with_invalid_gpg_signature = gpg: key 65E83E4964C370B3: public key "Test Miniportile <test@miniportile.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Wed Apr  6 15:33:28 2016 UTC
gpg:                using RSA key 65E83E4964C370B3
gpg: BAD signature from "Test Miniportile <test@miniportile.org>" [unknown]
0.34 s = .
TestDigest#test_with_invalid_key = gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
0.02 s = .
Downloading test-digest-1.0.0.tar.gz (100%) 127.0.0.1 - - [20/Dec/2021:08:34:25 UTC] "GET /test-digest-1.0.0.tar.gz HTTP/1.1" 200 244
- -> /test-digest-1.0.0.tar.gz

0.01 s = .
TestDigest#test_optional_gpg_signature_url = gpg: key 65E83E4964C370B3: public key "Test Miniportile <test@miniportile.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Wed Apr  6 16:24:31 2016 UTC
gpg:                using RSA key 65E83E4964C370B3
gpg: Good signature from "Test Miniportile <test@miniportile.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: A1BD 95B3 71E6 7B2A F4EA  E46B 65E8 3E49 64C3 70B3
0.03 s = .
Downloading test-digest-1.0.0.tar.gz (100%) 127.0.0.1 - - [20/Dec/2021:08:34:25 UTC] "GET /test-digest-1.0.0.tar.gz HTTP/1.1" 200 244
- -> /test-digest-1.0.0.tar.gz

0.01 s = .
Downloading test-digest-1.0.0.tar.gz (100%) 127.0.0.1 - - [20/Dec/2021:08:34:25 UTC] "GET /test-digest-1.0.0.tar.gz HTTP/1.1" 200 244
- -> /test-digest-1.0.0.tar.gz

0.01 s = .
Downloading test-digest-1.0.0.tar.gz (100%) 127.0.0.1 - - [20/Dec/2021:08:34:25 UTC] "GET /test-digest-1.0.0.tar.gz HTTP/1.1" 200 244
- -> /test-digest-1.0.0.tar.gz

0.01 s = .
Downloading test-digest-1.0.0.tar.gz (100%) 127.0.0.1 - - [20/Dec/2021:08:34:25 UTC] "GET /test-digest-1.0.0.tar.gz HTTP/1.1" 200 244

- -> /test-digest-1.0.0.tar.gz
0.01 s = .
TestDigest#test_with_different_key_than_one_used_to_sign = ################
gpg: key 520A9993A1C052F8: 4 signatures not checked due to missing keys
gpg: key 520A9993A1C052F8: public key "Maxim Dounin <mdounin@mdounin.ru>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no ultimately trusted keys found
gpg: Signature made Wed Apr  6 16:24:31 2016 UTC
gpg:                using RSA key 65E83E4964C370B3
gpg: Can't check signature: No public key
0.03 s = .
Downloading test-digest-1.0.0.tar.gz (100%) 127.0.0.1 - - [20/Dec/2021:08:34:25 UTC] "GET /test-digest-1.0.0.tar.gz HTTP/1.1" 200 244
- -> /test-digest-1.0.0.tar.gz

0.01 s = .
TestDigest#test_with_valid_gpg_signature = gpg: key 65E83E4964C370B3: public key "Test Miniportile <test@miniportile.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Wed Apr  6 16:24:31 2016 UTC
gpg:                using RSA key 65E83E4964C370B3
gpg: Good signature from "Test Miniportile <test@miniportile.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: A1BD 95B3 71E6 7B2A F4EA  E46B 65E8 3E49 64C3 70B3
0.02 s = .
[2021-12-20 08:34:25] INFO  going to shutdown ...
[2021-12-20 08:34:25] INFO  WEBrick::HTTPServer#start done.
[2021-12-20 08:34:25] INFO  WEBrick 1.6.0
[2021-12-20 08:34:25] INFO  ruby 2.7.2 (2020-10-01) [powerpc64le-linux]
[2021-12-20 08:34:25] INFO  WEBrick::HTTPServer#start: pid=210 port=23523
Downloading test-cmake-1.0.tar.gz (100%) 127.0.0.1 - - [20/Dec/2021:08:34:25 UTC] "GET /test-cmake-1.0.tar.gz HTTP/1.1" 200 406

**- -> /test-cmake-1.0.tar.gz
Extracting test-cmake-1.0.tar.gz into tmp/ppc64le-redhat-linux/ports/test-cmake/1.0... OK
Running git apply with /home/tester/mini_portile2/test/assets/patch 1.diff... OK
Running 'configure' for test-cmake 1.0... ERROR, review '/home/tester/mini_portile2/tmp/ppc64le-redhat-linux/ports/test-cmake/1.0/configure.log' to see what happened. Last lines are:
========================================================================
CMake Error: Unknown argument --option="path with 'space'"
CMake Error: Run 'cmake --help' for all supported options.
========================================================================**
0.00 s = E
[2021-12-20 08:34:25] INFO  going to shutdown ...
[2021-12-20 08:34:25] INFO  WEBrick::HTTPServer#start done.
recipe download::urls#test_0002_handles http = 2 retrie(s) left for foo
1 retrie(s) left for foo
0 retrie(s) left for foo
wrong status line: "CONNECTION SUCESSFULLY MADE"
DEPRECATED: global use of must_be from /home/tester/mini_portile2/test/test_download.rb:26. Use _(obj).must_be instead. This will fail in Minitest 6.
2.01 s = .
recipe download::urls#test_0005_other = DEPRECATED: global use of must_raise from /home/tester/mini_portile2/test/test_download.rb:68. Use _{obj.method}.must_raise instead. This will fail in Minitest 6.
0.01 s = .
recipe download::urls#test_0001_ftp = DEPRECATED: global use of must_be from /home/tester/mini_portile2/test/test_download.rb:26. Use _(obj).must_be instead. This will fail in Minitest 6.
0.01 s = .
recipe download::urls#test_0003_handles https = 2 retrie(s) left for foo
1 retrie(s) left for foo
0 retrie(s) left for foo
SSL_connect returned=1 errno=0 state=error: https proxy request
DEPRECATED: global use of must_be from /home/tester/mini_portile2/test/test_download.rb:26. Use _(obj).must_be instead. This will fail in Minitest 6.
2.04 s = .
recipe download::urls#test_0004_file = DEPRECATED: global use of must_equal from /home/tester/mini_portile2/test/test_download.rb:63. Use _(obj).must_equal instead. This will fail in Minitest 6.
0.01 s = .
TestProxy#test_ftp_proxy_with_basic_auth = 0.01 s = .
TestProxy#test_https_proxy_with_basic_auth = 2 retrie(s) left for tar.gz
1 retrie(s) left for tar.gz
0 retrie(s) left for tar.gz
Failed to open TCP connection to localhost:35257 (Cannot assign requested address - connect(2) for "localhost" port 35257)
2.04 s = .
TestProxy#test_ftp_proxy = 0.02 s = .
TestProxy#test_http_proxy = 2 retrie(s) left for tar.gz
1 retrie(s) left for tar.gz
0 retrie(s) left for tar.gz
Failed to open TCP connection to localhost:35919 (Cannot assign requested address - connect(2) for "localhost" port 35919)
2.05 s = .
TestProxy#test_http_proxy_with_basic_auth = 2 retrie(s) left for tar.gz
1 retrie(s) left for tar.gz
0 retrie(s) left for tar.gz
Failed to open TCP connection to localhost:38573 (Cannot assign requested address - connect(2) for "localhost" port 38573)
2.01 s = .
TestProxy#test_https_proxy = 2 retrie(s) left for tar.gz
1 retrie(s) left for tar.gz
0 retrie(s) left for tar.gz
Failed to open TCP connection to localhost:39481 (Cannot assign requested address - connect(2) for "localhost" port 39481)
2.08 s = .
[2021-12-20 08:34:38] INFO  WEBrick 1.6.0
[2021-12-20 08:34:38] INFO  ruby 2.7.2 (2020-10-01) [powerpc64le-linux]
[2021-12-20 08:34:38] INFO  WEBrick::HTTPServer#start: pid=210 port=23523
Downloading test%20mini%20portile-1.0.0.tar.gz (100%) 127.0.0.1 - - [20/Dec/2021:08:34:38 UTC] "GET /test%20mini%20portile-1.0.0.tar.gz HTTP/1.1" 200 244
- -> /test%20mini%20portile-1.0.0.tar.gz

Extracting test%20mini%20portile-1.0.0.tar.gz into tmp/ppc64le-redhat-linux/ports/test mini portile/1.0.0... OK
Running git apply with /home/tester/mini_portile2/test/assets/patch 1.diff... OK
Running 'configure' for test mini portile 1.0.0... OK
Running 'compile' for test mini portile 1.0.0... OK
Running 'install' for test mini portile 1.0.0... OK
TestCook#test_install = 0.00 s = .
TestCook#test_untar = 0.00 s = .
TestCook#test_configure = 0.00 s = .
TestCook#test_compile = 0.00 s = .
TestCook#test_patch = 0.00 s = .
TestCook#test_download = 0.00 s = .
[2021-12-20 08:34:39] INFO  going to shutdown ...
[2021-12-20 08:34:39] INFO  WEBrick::HTTPServer#start done.

Finished in 15.473530s, 1.9388 runs/s, 2.9728 assertions/s.

  1) Error:
TestCMake#before_all:
RuntimeError: Failed to complete configure task
    /home/tester/mini_portile2/lib/mini_portile2/mini_portile.rb:402:in `block in execute'
    /home/tester/mini_portile2/lib/mini_portile2/mini_portile.rb:373:in `chdir'
    /home/tester/mini_portile2/lib/mini_portile2/mini_portile.rb:373:in `execute'
    /home/tester/mini_portile2/lib/mini_portile2/mini_portile_cmake.rb:22:in `configure'
    /home/tester/mini_portile2/lib/mini_portile2/mini_portile.rb:153:in `cook'
    /home/tester/mini_portile2/test/test_cmake.rb:25:in `block (2 levels) in before_all'
    /home/tester/mini_portile2/test/helper.rb:56:in `with_custom_git_dir'
    /home/tester/mini_portile2/test/test_cmake.rb:24:in `block in before_all'
    /home/tester/mini_portile2/test/test_cmake.rb:19:in `tap'
    /home/tester/mini_portile2/test/test_cmake.rb:19:in `before_all'

30 runs, 46 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -W2 -I. -Ilib -e "require 'test/te...]
/home/tester/mini_portile2/Rakefile:8:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.7.2/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => test:unit
(See full trace by running task with --trace)

```

Any pointers on why does this error occur. Earlier this error was not present I guess

**Comment by flavorjones** [comment]
Hi, I'm sorry you're seeing this error, I'll try to help.

In the future, can I ask that you please take care to format your issues to be more readable, or attach long logs instead of inlining them? I am going to reformat it now.

**Comment by flavorjones** [comment]
Please upgrade mini_portile2. af333cd removed this test from the cmake suite in v2.5.1.

**Comment by saurabhghumnar** [comment]
Great, will do. Thanks for the quick reply !
